kind: Service
apiVersion: v1
metadata:
  name: f1-booking-service
  labels:
    app: f1-booking-service
spec:
  type: NodePort
  selector:
    app: f1-booking-service
  ports:
  - port: 7000
    targetPort: 7000
    name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-booking-service
  labels:
    app: f1-booking-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-booking-service
      version: v1
  template:
    metadata:
      labels:
        app: f1-booking-service
        version: v1
    spec:
      containers:
        - name: seat-booking-service
          image: f1/f1-booking-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000